# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Action to checkout your repository code

      - name: Set up Python
        uses: actions/setup-python@v4 # Action to set up Python
        with:
          python-version: '3.9' # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8 linter
        run: |
          flake8 src/ tests/ # Check src and tests directories
        # You might want to add a config file for flake8 (.flake8) for custom rules

      - name: Run Pytest unit tests
        run: |
          pytest tests/ # Run tests in the tests/ directory
        # Pytest will automatically discover tests

